before:
  hooks:
    - go mod tidy

builds:
  - id: "gh-repo-visualize"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gh-repo-visualize/main.go 
    binary: gh-repo-visualize
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}} -X main.BuildCommit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - typo

release:
  github:
    owner: h1s97x
    name: gh-repo-visualize

brews:
  - name: gh-repo-visualize
    homepage: "https://github.com/h1s97x/gh-repo-visualize"
    description: "A GitHub CLI extension for visualizing Git commit history"
    repository:
      owner: h1s97x
      name: homebrew-tap
    install: |
      bin.install "gh-repo-visualize"
